export const DIRECTIVES = [
    { value: 'wcag1', tag: '#perceivable', label: 'Perceivable' },
    
    { value: 'wcag11', tag: '#text-alternatives', label: 'Text Alternatives' },
    { value: 'wcag111', tag: '#non-text-content', label: 'Non-text Content' },
  
    { value: 'wcag12', tag: '#time-based-media', label: 'Time-based Media' },
    { value: 'wcag121', tag: '#audio-only-and-video-only-prerecorded', label: 'Audio-only and Video-only (Prerecorded)' },
    { value: "wcag122", tag: "#time-based-media", label: "Time-based Media" },
    { value: "wcag123", tag: "#audio-description-or-media-alternative-prerecorded", label: "Audio Description or Media Alternative (Prerecorded)" },
    { value: "wcag124", tag: "#captions-live", label: "Captions (Live)" },
    { value: "wcag125", tag: "#audio-description-prerecorded", label: "Audio Description (Prerecorded)" },
    { value: "wcag126", tag: "#sign-language-prerecorded", label: "Sign Language (Prerecorded)" },
    { value: "wcag127", tag: "#extended-audio-description-prerecorded", label: "Extended Audio Description (Prerecorded)" },
    { value: "wcag128", tag: "#media-alternative-prerecorded", label: "Media Alternative (Prerecorded)" },
    { value: "wcag129", tag: "#audio-only-live", label: "Audio-only (Live)" },
  
    { value: "wcag13", tag: "#adaptable", label: "Adaptable" },
    { value: "wcag131", tag: "#info-and-relationships", label: "Info and Relationships" },
    { value: "wcag132", tag: "#meaningful-sequence", label: "Meaningful Sequence" },
    { value: "wcag133", tag: "#sensory-characteristics", label: "Sensory Characteristics" },
    { value: "wcag134", tag: "#orientation", label: "Orientation" },
    { value: "wcag135", tag: "#identify-input-purpose", label: "Identify Input Purpose" },
    { value: "wcag136", tag: "#identify-purpose", label: "Identify Purpose" },
  
    { value: "wcag14", tag: "#distinguishable", label: "Distinguishable" },
    { value: "wcag141", tag: "#use-of-color", label: "Use of Color" },
    { value: "wcag142", tag: "#audio-control", label: "Audio Control" },
    { value: "wcag143", tag: "#contrast-minimum", label: "Contrast (Minimum)" },
    { value: "wcag144", tag: "#resize-text", label: "Resize Text" },
    { value: "wcag145", tag: "#images-of-text", label: "Images of Text" },
    { value: "wcag146", tag: "#contrast-enhanced", label: "Contrast (Enhanced)" },
    { value: "wcag147", tag: "#low-or-no-background-audio", label: "Low or No Background Audio" },
    { value: "wcag148", tag: "#visual-presentation", label: "Visual Presentation" },
    { value: "wcag149", tag: "#images-of-text-no-exception", label: "Images of Text (No Exception)" },
    { value: "wcag1410", tag: "#reflow", label: "Reflow" },
    { value: "wcag1411", tag: "#non-text-contrast", label: "Non-text Contrast" },
    { value: 'wcag1412', tag: '#text-spacing', label: 'Text Spacing' },
    { value: 'wcag1413', tag: '#content-on-hover-or-focus', label: 'Content on Hover or Focus' },
  
    { value: 'wcag2', tag: '#operable', label: 'Operable' },
    { value: 'wcag21', tag: '#keyboard-accessible', label: 'Keyboard Accessible' },
    { value: 'wcag211', tag: '#keyboard', label: 'Keyboard' },
    { value: 'wcag212', tag: '#no-keyboard-trap', label: 'No Keyboard Trap' },
    { value: 'wcag213', tag: '#keyboard-no-exception', label: 'Keyboard (No Exception)' },
    { value: 'wcag214', tag: '#character-key-shortcuts', label: 'Character Key Shortcuts' },
  
    { value: 'wcag22', tag: '#enough-time', label: 'Enough Time' },
    { value: 'wcag221', tag: '#timing-adjustable', label: 'Timing Adjustable' },
    { value: 'wcag222', tag: '#pause-stop-hide', label: 'Pause, Stop, Hide' },
    { value: 'wcag223', tag: '#no-timing', label: 'No Timing' },
    { value: 'wcag224', tag: '#interruptions', label: 'Interruptions' },
    { value: 'wcag225', tag: '#re-authenticating', label: 'Re-authenticating' },
    { value: 'wcag226', tag: '#timeouts', label: 'Timeouts' },
  
    { value: 'wcag23', tag: '#seizures-and-physical-reactions', label: 'Seizures and Physical Reactions' },
    { value: 'wcag231', tag: '#three-flashes-or-below-threshold', label: 'Three Flashes or Below Threshold' },
    { value: 'wcag232', tag: '#three-flashes', label: 'Three Flashes' },
    { value: 'wcag233', tag: '#animation-from-interactions', label: 'Animation from Interactions' },
  
    { value: 'wcag24', tag: '#navigable', label: 'Navigable' },
    { value: 'wcag241', tag: '#bypass-blocks', label: 'Bypass Blocks' },
    { value: 'wcag242', tag: '#page-titled', label: 'Page Titled' },
    { value: 'wcag243', tag: '#focus-order', label: 'Focus Order' },
    { value: 'wcag244', tag: '#link-purpose-in-context', label: 'Link Purpose (In Context)' },
    { value: 'wcag245', tag: '#multiple-ways', label: 'Multiple Ways' },
    { value: 'wcag246', tag: '#headings-and-labels', label: 'Headings and Labels' },
    { value: 'wcag247', tag: '#focus-visible', label: 'Focus Visible' },
    { value: 'wcag248', tag: '#location', label: 'Location' },
    { value: 'wcag249', tag: '#link-purpose-link-only', label: 'Link Purpose (Link Only)' },
    { value: 'wcag2410', tag: '#section-headings', label: 'Section Headings' },
  
    { value: 'wcag25', tag: '#input-modalities', label: 'Input Modalities' },
    { value: 'wcag251', tag: '#pointer-gestures', label: 'Pointer Gestures' },
    { value: 'wcag252', tag: '#pointer-cancellation', label: 'Pointer Cancellation' },
    { value: 'wcag253', tag: '#label-in-name', label: 'Label in Name' },
    { value: 'wcag254', tag: '#motion-actuation', label: 'Motion Actuation' },
    { value: 'wcag255', tag: '#target-size', label: 'Target Size' },
    { value: 'wcag256', tag: '#concurrent-input-mechanisms', label: 'Concurrent Input Mechanisms' },
  
    { value: 'wcag31', tag: '#readable', label: 'Readable' },
    { value: 'wcag311', tag: '#language-of-page', label: 'Language of Page' },
    { value: 'wcag312', tag: '#language-of-parts', label: 'Language of Parts' },
    { value: 'wcag313', tag: '#unusual-words', label: 'Unusual Words' },
    { value: 'wcag314', tag: '#abbreviations', label: 'Abbreviations' },
    { value: 'wcag315', tag: '#reading-level', label: 'Reading Level' },
    { value: 'wcag316', tag: '#pronunciation', label: 'Pronunciation' },
  
    { value: 'wcag32', tag: '#predictable', label: 'Predictable' },
    { value: 'wcag321', tag: '#on-focus', label: 'On Focus' },
    { value: 'wcag322', tag: '#on-input', label: 'On Input' },
    { value: 'wcag323', tag: '#consistent-navigation', label: 'Consistent Navigation' },
    { value: 'wcag324', tag: '#consistent-identification', label: 'Consistent Identification' },
    { value: 'wcag325', tag: '#change-on-request', label: 'Change on Request' },
  
    { value: 'wcag33', tag: '#input-assistance', label: 'Input Assistance' },
    { value: 'wcag331', tag: '#error-identification', label: 'Error Identification' },
    { value: 'wcag332', tag: '#labels-or-instructions', label: 'Labels or Instructions' },
    { value: 'wcag333', tag: '#error-suggestion', label: 'Error Suggestion' },
    { value: 'wcag334', tag: '#error-prevention-legal-financial-data', label: 'Error Prevention (Legal, Financial, Data)' },
    { value: 'wcag335', tag: '#help', label: 'Help' },
    { value: 'wcag336', tag: '#error-prevention-all', label: 'Error Prevention (All)' },
  
    { value: 'wcag341', tag: '#reversible-operations', label: 'Reversible Operations' },
    { value: 'wcag342', tag: '#consistent-navigation', label: 'Consistent Navigation' },

    { value: 'wcag1', tag: '#perceivable' },

    { value: 'wcag11', tag: '#text-alternatives' },
    { value: 'wcag111', tag: '#non-text-content' },

    { value: 'wcag12', tag: '#time-based-media' },
    { value: 'wcag121', tag: '#audio-only-and-video-only-prerecorded' },
    { value: "wcag122",tag: "#time-based-media" },
    { value: "wcag123",tag: "#audio-description-or-media-alternative-prerecorded" },
    { value: "wcag124",tag: "#captions-live" },
    { value: "wcag125",tag: "#audio-description-prerecorded" },
    { value: "wcag126",tag: "#sign-language-prerecorded" },
    { value: "wcag127",tag: "#extended-audio-description-prerecorded" },
    { value: "wcag128",tag: "#media-alternative-prerecorded" },
    { value: "wcag129",tag: "#audio-only-live" },
  
    { value: "wcag13", tag: "#adaptable" },
    { value: "wcag131",tag: "#info-and-relationships" },
    { value: "wcag132",tag: "#meaningful-sequence" },
    { value: "wcag133",tag: "#sensory-characteristics" },
    { value: "wcag134",tag: "#orientation" },
    { value: "wcag135",tag: "#identify-input-purpose" },
    { value: "wcag136",tag: "#identify-purpose" },

    { value: "wcag14", tag: "#distinguishable" },
    { value: "wcag141",tag: "#use-of-color" },
    { value: "wcag142",tag: "#audio-control" },
    { value: "wcag143",tag: "#contrast-minimum" },
    { value: "wcag144",tag: "#resize-text" },
    { value: "wcag145",tag: "#images-of-text" },
    { value: "wcag146",tag: "#contrast-enhanced" },
    { value: "wcag147",tag: "#low-or-no-background-audio" },
    { value: "wcag148",tag: "#visual-presentation" },
    { value: "wcag149",tag: "#images-of-text-no-exception" },
    { value: "wcag1410", tag: "#reflow" },
    { value: "wcag1411", tag: "#non-text-contrast" },
    { value: 'wcag1412', tag: '#text-spacing' },
    { value: 'wcag1413', tag: '#content-on-hover-or-focus' },

    { value: 'wcag2', tag: '#operable' },
    { value: 'wcag21', tag: '#keyboard-accessible' },
    { value: 'wcag211', tag: '#keyboard' },
    { value: 'wcag212', tag: '#no-keyboard-trap' },
    { value: 'wcag213', tag: '#keyboard-no-exception' },
    { value: 'wcag214', tag: '#character-key-shortcuts' },

    { value: 'wcag22', tag: '#enough-time' },
    { value: 'wcag221', tag: '#timing-adjustable' },
    { value: 'wcag222', tag: '#pause-stop-hide' },
    { value: 'wcag223', tag: '#no-timing' },
    { value: 'wcag224', tag: '#interruptions' },
    { value: 'wcag225', tag: '#re-authenticating' },
    { value: 'wcag226', tag: '#timeouts' },

    { value: 'wcag23', tag: '#seizures-and-physical-reactions' },
    { value: 'wcag231', tag: '#three-flashes-or-below-threshold' },
    { value: 'wcag232', tag: '#three-flashes' },
    { value: 'wcag233', tag: '#animation-from-interactions' },

    { value: 'wcag24', tag: '#navigable' },
    { value: 'wcag241', tag: '#bypass-blocks' },
    { value: 'wcag242', tag: '#page-titled' },
    { value: 'wcag243', tag: '#focus-order' },
    { value: 'wcag244', tag: '#link-purpose-in-context' },
    { value: 'wcag245', tag: '#multiple-ways' },
    { value: 'wcag246', tag: '#headings-and-labels' },
    { value: 'wcag247', tag: '#focus-visible' },
    { value: 'wcag248', tag: '#location' },
    { value: 'wcag249', tag: '#link-purpose-link-only' },
    { value: 'wcag2410', tag: '#section-headings' },

    { value: 'wcag25', tag: '#input-modalities' },
    { value: 'wcag251', tag: '#pointer-gestures' },
    { value: 'wcag252', tag: '#pointer-cancellation' },
    { value: 'wcag253', tag: '#label-in-name' },
    { value: 'wcag254', tag: '#motion-actuation' },
    { value: 'wcag255', tag: '#target-size' },
    { value: 'wcag256', tag: '#concurrent-input-mechanisms' },

    { value: 'wcag31', tag: '#readable' },
    { value: 'wcag311', tag: '#language-of-page' },
    { value: 'wcag312', tag: '#language-of-parts' },
    { value: 'wcag313', tag: '#unusual-words' },
    { value: 'wcag314', tag: '#abbreviations' },
    { value: 'wcag315', tag: '#reading-level' },
    { value: 'wcag316', tag: '#pronunciation' },

    { value: 'wcag32', tag: '#predictable' },
    { value: 'wcag321', tag: '#on-focus' },
    { value: 'wcag322', tag: '#on-input' },
    { value: 'wcag323', tag: '#consistent-navigation' },
    { value: 'wcag324', tag: '#consistent-identification' },
    { value: 'wcag325', tag: '#change-on-request' },

    { value: 'wcag33', tag: '#input-assistance' },
    { value: 'wcag331', tag: '#error-identification' },
    { value: 'wcag332', tag: '#labels-or-instructions' },
    { value: 'wcag333', tag: '#error-suggestion' },
    { value: 'wcag334', tag: '#error-prevention-legal-financial-data' },
    { value: 'wcag335', tag: '#help' },
    { value: 'wcag336', tag: '#error-prevention-all' },

    { value: 'wcag4', tag: '#robust' },
    { value: 'wcag41', tag: '#compatible' },
    { value: 'wcag411', tag: '#parsing' },
    { value: 'wcag412', tag: '#name-role-value' },
    { value: 'wcag413', tag: '#status-messages' },

    { value: 'wcag5', tag: '#conformance' },
    { value: 'wcag51', tag: '#interpreting-normative-requirements' },
    { value: 'wcag52', tag: '#conformance-reqs' },
    { value: 'wcag521', tag: '#cc1' },
    { value: 'wcag522', tag: '#cc2' },
    { value: 'wcag523', tag: '#cc3' },
    { value: 'wcag524', tag: '#cc4' },
    { value: 'wcag525', tag: '#cc5' },
    { value: 'wcag53', tag: '#conformance-claims' },
    { value: 'wcag531', tag: '#conformance-required' },
    { value: 'wcag532', tag: '#conformance-optional' },
    { value: 'wcag54', tag: '#conformance-partial' },
    { value: 'wcag55', tag: '#conformance-partial-lang' },
  ];