export const DIRECTIVES = [
    { value: 'wcag1', tag: '#perceivable' },

    { value: 'wcag11', tag: '#text-alternatives' },
    { value: 'wcag111', tag: '#non-text-content' },

    { value: 'wcag12', tag: '#time-based-media' },
    { value: 'wcag121', tag: '#audio-only-and-video-only-prerecorded' },
    { value: "wcag122",tag: "#time-based-media" },
    { value: "wcag123",tag: "#audio-description-or-media-alternative-prerecorded" },
    { value: "wcag124",tag: "#captions-live" },
    { value: "wcag125",tag: "#audio-description-prerecorded" },
    { value: "wcag126",tag: "#sign-language-prerecorded" },
    { value: "wcag127",tag: "#extended-audio-description-prerecorded" },
    { value: "wcag128",tag: "#media-alternative-prerecorded" },
    { value: "wcag129",tag: "#audio-only-live" },
  
    { value: "wcag13", tag: "#adaptable" },
    { value: "wcag131",tag: "#info-and-relationships" },
    { value: "wcag132",tag: "#meaningful-sequence" },
    { value: "wcag133",tag: "#sensory-characteristics" },
    { value: "wcag134",tag: "#orientation" },
    { value: "wcag135",tag: "#identify-input-purpose" },
    { value: "wcag136",tag: "#identify-purpose" },

    { value: "wcag14", tag: "#distinguishable" },
    { value: "wcag141",tag: "#use-of-color" },
    { value: "wcag142",tag: "#audio-control" },
    { value: "wcag143",tag: "#contrast-minimum" },
    { value: "wcag144",tag: "#resize-text" },
    { value: "wcag145",tag: "#images-of-text" },
    { value: "wcag146",tag: "#contrast-enhanced" },
    { value: "wcag147",tag: "#low-or-no-background-audio" },
    { value: "wcag148",tag: "#visual-presentation" },
    { value: "wcag149",tag: "#images-of-text-no-exception" },
    { value: "wcag1410", tag: "#reflow" },
    { value: "wcag1411", tag: "#non-text-contrast" },
    { value: 'wcag1412', tag: '#text-spacing' },
    { value: 'wcag1413', tag: '#content-on-hover-or-focus' },

    { value: 'wcag2', tag: '#operable' },
    { value: 'wcag21', tag: '#keyboard-accessible' },
    { value: 'wcag211', tag: '#keyboard' },
    { value: 'wcag212', tag: '#no-keyboard-trap' },
    { value: 'wcag213', tag: '#keyboard-no-exception' },
    { value: 'wcag214', tag: '#character-key-shortcuts' },

    { value: 'wcag22', tag: '#enough-time' },
    { value: 'wcag221', tag: '#timing-adjustable' },
    { value: 'wcag222', tag: '#pause-stop-hide' },
    { value: 'wcag223', tag: '#no-timing' },
    { value: 'wcag224', tag: '#interruptions' },
    { value: 'wcag225', tag: '#re-authenticating' },
    { value: 'wcag226', tag: '#timeouts' },

    { value: 'wcag23', tag: '#seizures-and-physical-reactions' },
    { value: 'wcag231', tag: '#three-flashes-or-below-threshold' },
    { value: 'wcag232', tag: '#three-flashes' },
    { value: 'wcag233', tag: '#animation-from-interactions' },

    { value: 'wcag24', tag: '#navigable' },
    { value: 'wcag241', tag: '#bypass-blocks' },
    { value: 'wcag242', tag: '#page-titled' },
    { value: 'wcag243', tag: '#focus-order' },
    { value: 'wcag244', tag: '#link-purpose-in-context' },
    { value: 'wcag245', tag: '#multiple-ways' },
    { value: 'wcag246', tag: '#headings-and-labels' },
    { value: 'wcag247', tag: '#focus-visible' },
    { value: 'wcag248', tag: '#location' },
    { value: 'wcag249', tag: '#link-purpose-link-only' },
    { value: 'wcag2410', tag: '#section-headings' },

    { value: 'wcag25', tag: '#input-modalities' },
    { value: 'wcag251', tag: '#pointer-gestures' },
    { value: 'wcag252', tag: '#pointer-cancellation' },
    { value: 'wcag253', tag: '#label-in-name' },
    { value: 'wcag254', tag: '#motion-actuation' },
    { value: 'wcag255', tag: '#target-size' },
    { value: 'wcag256', tag: '#concurrent-input-mechanisms' },

    { value: 'wcag31', tag: '#readable' },
    { value: 'wcag311', tag: '#language-of-page' },
    { value: 'wcag312', tag: '#language-of-parts' },
    { value: 'wcag313', tag: '#unusual-words' },
    { value: 'wcag314', tag: '#abbreviations' },
    { value: 'wcag315', tag: '#reading-level' },
    { value: 'wcag316', tag: '#pronunciation' },

    { value: 'wcag32', tag: '#predictable' },
    { value: 'wcag321', tag: '#on-focus' },
    { value: 'wcag322', tag: '#on-input' },
    { value: 'wcag323', tag: '#consistent-navigation' },
    { value: 'wcag324', tag: '#consistent-identification' },
    { value: 'wcag325', tag: '#change-on-request' },

    { value: 'wcag33', tag: '#input-assistance' },
    { value: 'wcag331', tag: '#error-identification' },
    { value: 'wcag332', tag: '#labels-or-instructions' },
    { value: 'wcag333', tag: '#error-suggestion' },
    { value: 'wcag334', tag: '#error-prevention-legal-financial-data' },
    { value: 'wcag335', tag: '#help' },
    { value: 'wcag336', tag: '#error-prevention-all' },

    { value: 'wcag4', tag: '#robust' },
    { value: 'wcag41', tag: '#compatible' },
    { value: 'wcag411', tag: '#parsing' },
    { value: 'wcag412', tag: '#name-role-value' },
    { value: 'wcag413', tag: '#status-messages' },

    { value: 'wcag5', tag: '#conformance' },
    { value: 'wcag51', tag: '#interpreting-normative-requirements' },
    { value: 'wcag52', tag: '#conformance-reqs' },
    { value: 'wcag521', tag: '#cc1' },
    { value: 'wcag522', tag: '#cc2' },
    { value: 'wcag523', tag: '#cc3' },
    { value: 'wcag524', tag: '#cc4' },
    { value: 'wcag525', tag: '#cc5' },
    { value: 'wcag53', tag: '#conformance-claims' },
    { value: 'wcag531', tag: '#conformance-required' },
    { value: 'wcag532', tag: '#conformance-optional' },
    { value: 'wcag54', tag: '#conformance-partial' },
    { value: 'wcag55', tag: '#conformance-partial-lang' },
  ];