export const DIRECTIVES = [
    { value: '2.1.1', label: '2.1.1 - Keyboard Accessible' },
    { value: '2.1.2', label: '2.1.2 - No Keyboard Trap' },
    { value: '2.1.4', label: '2.1.4 - Character Key Shortcuts' },
    { value: '2.2.1', label: '2.2.1 - Timing Adjustable' },
    { value: '2.2.2', label: '2.2.2 - Pause, Stop, Hide' },
    { value: '2.2.4', label: '2.2.4 - Interruptions' },
    { value: '2.2.5', label: '2.2.5 - Re-authenticating' },
    { value: '2.2.6', label: '2.2.6 - Timeouts' },
    { value: '2.3.1', label: '2.3.1 - Three Flashes or Below Threshold' },
    { value: '2.3.2', label: '2.3.2 - Three Flashes' },
    { value: '2.3.3', label: '2.3.3 - Animation from Interactions' },
    { value: '2.4.1', label: '2.4.1 - Bypass Blocks' },
    { value: '2.4.2', label: '2.4.2 - Page Titled' },
    { value: '2.4.3', label: '2.4.3 - Focus Order' },
    { value: '2.4.4', label: '2.4.4 - Link Purpose (In Context)' },
    { value: '2.4.5', label: '2.4.5 - Multiple Ways' },
    { value: '2.4.6', label: '2.4.6 - Headings and Labels' },
    { value: '2.4.7', label: '2.4.7 - Focus Visible' },
    { value: '2.4.8', label: '2.4.8 - Location' },
    { value: '2.4.9', label: '2.4.9 - Link Purpose (Link Only)' },
    { value: '2.4.10', label: '2.4.10 - Section Headings' },
    { value: '3.1.1', label: '3.1.1 - Language of Page' },
    { value: '3.1.2', label: '3.1.2 - Language of Parts' },
    { value: '3.1.3', label: '3.1.3 - Unusual Words' },
    { value: '3.1.4', label: '3.1.4 - Abbreviations' },
    { value: '3.1.5', label: '3.1.5 - Reading Level' },
    { value: '3.1.6', label: '3.1.6 - Pronunciation' },
    { value: '3.2.1', label: '3.2.1 - On Focus' },
    { value: '3.2.2', label: '3.2.2 - On Input' },
    { value: '3.2.3', label: '3.2.3 - Consistent Navigation' },
    { value: '3.2.4', label: '3.2.4 - Consistent Identification' },
    { value: '3.2.5', label: '3.2.5 - Change on Request' },
    { value: '3.3.1', label: '3.3.1 - Error Identification' },
    { value: '3.3.2', label: '3.3.2 - Labels or Instructions' },
    { value: '3.3.3', label: '3.3.3 - Error Suggestion' },
    { value: '3.3.4', label: '3.3.4 - Error Prevention (Legal, Financial, Data)' },
    { value: '3.3.5', label: '3.3.5 - Help' },
    { value: '3.3.6', label: '3.3.6 - Error Prevention (All)' },
    { value: '4.1.1', label: '4.1.1 - Parsing' },
    { value: '4.1.2', label: '4.1.2 - Name, Role, Value' },
    { value: '4.1.3', label: '4.1.3 - Status Messages' },
  ];